const fs = require('fs');
const path = require('path');

const dirPath = __dirname;
const files = fs.readdirSync(dirPath);

const photos = [];
const videos = [];

files.forEach(file => {
  const ext = path.extname(file).toLowerCase();
  // Match photos
  if (ext === '.jpg' || ext === '.jpeg' || ext === '.png') {
    if (file.startsWith('photo_')) {
      photos.push(file);
    }
  }
  // Match videos
  if (ext === '.mov' || ext === '.mp4') {
    if (file.startsWith('IMG_')) {
      videos.push(file);
    }
  }
});

// Sort photos by their number in the filename for consistency (photo_1_... vs photo_10_...)
const getPhotoNumber = (filename) => {
  const match = filename.match(/photo_(\d+)_/);
  return match ? parseInt(match[1], 10) : Infinity;
};
photos.sort((a, b) => getPhotoNumber(a) - getPhotoNumber(b));

// Sort videos as well
videos.sort();

const outputContent = `// Automatically generated by index-media.js
export const mediaIndex = {
  photos: ${JSON.stringify(photos, null, 2)},
  videos: ${JSON.stringify(videos, null, 2)}
};
`;

fs.writeFileSync(path.join(dirPath, 'media-index.js'), outputContent, 'utf8');
console.log(`Successfully indexed ${photos.length} photos and ${videos.length} videos into media-index.js`);
